// A surfboard silhouette, stroked from the artist's real outlines.
//
// See specs/board-selection.md D6. Two jobs, one widget:
//
//   - The game screen carries ONE of these, small, landscape, top-left: which board you are riding,
//     and nothing else. No explanation, because a board needs none.
//   - The picker stands all five in a rack. There the silhouettes must share ONE scale, because the
//     size difference IS the information - a foamie is 1.56x a shortboard and the drawing says so
//     without a word of copy. That is what PixelsPerUnit exists for: the rack picks one value and
//     hands it to every glyph, instead of each fitting its own box and flattening the difference.
//
// Shapes come from BoardOutlineShapes.inc, generated by Tools/svg2boards.py from
// images/"surfboards outline.svg". Drawn rather than imported, for the reasons STutorialBoardGlyph
// gives: it stays vector at any size, it tints per state, and it needs no texture asset.
#pragma once

#include "CoreMinimal.h"
#include "Widgets/SLeafWidget.h"
#include "Components/Widget.h"
#include "BoardOutlineGlyph.generated.h"

/** Which way the board points. */
UENUM(BlueprintType)
enum class EBoardGlyphFacing : uint8
{
	/** Nose up. The rack. */
	NoseUp,
	/** Nose right. The small button, where a landscape strip costs far less height. */
	NoseRight,
};

namespace BoardOutline
{
	/** Stroke lists for a shape id ("foamie", "fish", ...), in board units: x along the board with
	 *  +x at the nose, y across it. False if the id is unknown.
	 *
	 *  OutWeights runs parallel to OutStrokes: 1.0 is the board outline, and the drawing's own
	 *  stroke-widths give the rest - a stringer comes out around a third, as drawn, so it stays
	 *  thinner than the rail it sits inside. */
	GONESURFING_API bool GetShape(const FString& ShapeId, TArray<TArray<FVector2f>>& OutStrokes,
		TArray<float>& OutWeights);

	/** Normalised length/width of a shape, on the scale every board shares (longest = 2.0).
	 *  False for an unknown id. */
	GONESURFING_API bool GetExtent(const FString& ShapeId, float& OutLength, float& OutWidth);

	/** Every shape id in the generated table, in rack order. */
	GONESURFING_API void GetAllShapeIds(TArray<FString>& OutIds);
}

class SBoardOutlineGlyph : public SLeafWidget
{
public:
	SLATE_BEGIN_ARGS(SBoardOutlineGlyph)
		: _LineColor(FLinearColor::White)
		, _Thickness(1.5f)
		, _PixelsPerUnit(0.0f)
		, _Facing(EBoardGlyphFacing::NoseUp)
	{}
		SLATE_ATTRIBUTE(FString, ShapeId)
		SLATE_ATTRIBUTE(FLinearColor, LineColor)
		SLATE_ATTRIBUTE(float, Thickness)
		/** > 0 pins the scale so several glyphs can share it and their relative sizes stay true; the
		 *  widget then asks for exactly the space its own board needs. 0 = fit the allotted box,
		 *  which is what a lone button wants. */
		SLATE_ATTRIBUTE(float, PixelsPerUnit)
		/** Attribute, not argument: the rack lays the SELECTED board down to landscape to buy back
		 *  the height its description needs, and selection moves while the cards are on screen. */
		SLATE_ATTRIBUTE(EBoardGlyphFacing, Facing)
		/** Bound = the glyph becomes clickable and tracks hover/press. Unbound = inert artwork. */
		SLATE_EVENT(FSimpleDelegate, OnClicked)
	SLATE_END_ARGS()

	void Construct(const FArguments& InArgs);

	virtual int32 OnPaint(const FPaintArgs& Args, const FGeometry& AllottedGeometry,
		const FSlateRect& MyCullingRect, FSlateWindowElementList& OutDrawElements,
		int32 LayerId, const FWidgetStyle& InWidgetStyle, bool bParentEnabled) const override;

	virtual FVector2D ComputeDesiredSize(float) const override;

	// ---- Interaction. The glyph IS the button: it tracks its own hover/press and reports clicks,
	// so a board control is one widget with one event to bind rather than a UButton plus four event
	// wires per board to keep a child in step with its parent's state.
	virtual FReply OnMouseButtonDown(const FGeometry& Geometry, const FPointerEvent& Event) override;
	virtual FReply OnMouseButtonUp(const FGeometry& Geometry, const FPointerEvent& Event) override;
	virtual void OnMouseEnter(const FGeometry& Geometry, const FPointerEvent& Event) override;
	virtual void OnMouseLeave(const FPointerEvent& Event) override;

	bool IsHoveredNow() const { return bHovered; }
	bool IsPressed() const { return bPressed; }

private:
	TAttribute<FString> ShapeId;
	TAttribute<FLinearColor> LineColor;
	TAttribute<float> Thickness;
	TAttribute<float> PixelsPerUnit;
	TAttribute<EBoardGlyphFacing> Facing;
	FSimpleDelegate OnClicked;

	/** Touch screens have no hover - a finger is either down or not there. So bHovered is a
	 *  desktop-only affordance and bPressed is the one that matters on the phone. */
	bool bHovered = false;
	bool bPressed = false;
};

/** UMG wrapper, for building board controls in a widget blueprint. */
UCLASS()
class GONESURFING_API UBoardOutlineWidget : public UWidget
{
	GENERATED_BODY()

public:
	/** Which board to draw. -1 (or no profile at that index) falls back to ShapeId below, which is
	 *  also what the UMG designer preview uses - there is no game instance at design time. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board")
	int32 BoardIndex = -1;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board")
	FString ShapeId = TEXT("foamie");

	/** Draw whichever board is currently being ridden, whatever that is. This is what a HUD button
	 *  wants - a readout of the live selection, not a fixed board - so the icon can never fall out of
	 *  step with the board underneath the player. Overrides BoardIndex.
	 *
	 *  Defaults TRUE, and did not at first. Off, the widget silently fell back to ShapeId's default
	 *  of "foamie", so a button showed a soft-top outline for ever while its label read the right
	 *  name - wrong, but plausible enough to look intentional. A default that produces a believable
	 *  lie is worse than one that produces nothing, so the common case is now the default; untick it
	 *  only to pin a specific board. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board")
	bool bShowActiveBoard = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board")
	EBoardGlyphFacing Facing = EBoardGlyphFacing::NoseUp;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board|Style")
	FLinearColor LineColor = FLinearColor(1.0f, 1.0f, 1.0f, 0.62f);

	/** Used instead of LineColor while this board is the active one. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board|Style")
	FLinearColor SelectedColor = FLinearColor(0.42f, 0.78f, 1.0f, 0.98f);

	/** Desktop only - a touch screen has no hover. Do not put anything the player must notice here;
	 *  PressedColor carries the phone. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board|Style")
	FLinearColor HoveredColor = FLinearColor(1.0f, 1.0f, 1.0f, 0.92f);

	/** The one interaction state a phone has, so it must be unmistakable alone. Brightened AND
	 *  thickened, because under a finger the thing that changed is the thing being covered. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board|Style")
	FLinearColor PressedColor = FLinearColor(1.0f, 0.86f, 0.42f, 1.0f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board|Style")
	float Thickness = 1.5f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board|Style")
	float SelectedThicknessScale = 1.4f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board|Style")
	float PressedThicknessScale = 1.8f;

	/** Leave true and the glyph tracks the real selection, so the bar cannot drift out of step with
	 *  the board actually being ridden. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board")
	bool bFollowActiveBoard = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Board")
	bool bSelected = false;

	UFUNCTION(BlueprintCallable, Category="Board")
	void SetBoardIndex(int32 InIndex);

	UFUNCTION(BlueprintCallable, Category="Board")
	void SetSelected(bool bInSelected);

	/** Bind this and the glyph becomes the button. Leave unbound for inert artwork. */
	DECLARE_DYNAMIC_MULTICAST_DELEGATE(FBoardOutlineClicked);
	UPROPERTY(BlueprintAssignable, Category="Board")
	FBoardOutlineClicked OnClicked;

	/** Public so the glyph's attribute lambdas can reach them through a weak pointer. */
	FString ResolveShapeId() const;
	bool ResolveSelected() const;
	FLinearColor ResolveColor() const;
	float ResolveThickness() const;

	virtual void SynchronizeProperties() override;
	virtual void ReleaseSlateResources(bool bReleaseChildren) override;
#if WITH_EDITOR
	virtual const FText GetPaletteCategory() override;
#endif

protected:
	virtual TSharedRef<SWidget> RebuildWidget() override;

private:
	TSharedPtr<SBoardOutlineGlyph> Glyph;
};
