# Convert the hand-drawn surfboard SVGs into the point lists TutorialBoardGlyph already strokes.
# Route A from the two options: keeps the glyph vector, tintable for the success flash, and needs
# no texture asset.
#
# Handles the subset Inkscape emitted here: relative m / c / z. Everything is sampled to polylines
# and normalised into the glyph's box: x scaled so the HULL spans -1..1, y by the same factor
# (aspect preserved), centred on the hull.
import re, sys, io

NUM = re.compile(r'[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?')

def parse_path(d):
    """-> list of subpaths, each a list of absolute (x,y) points sampled along the curves."""
    toks = re.findall(r'[MmCcZzLl]|' + NUM.pattern, d)
    i = 0
    cur = (0.0, 0.0)
    start = (0.0, 0.0)
    out, sub = [], []
    cmd = None
    while i < len(toks):
        t = toks[i]
        if t in 'MmCcZzLl':
            cmd = t
            i += 1
            if cmd in 'Zz':
                if sub:
                    sub.append(start)
                    out.append(sub); sub = []
                cur = start
                continue
        nums = []
        need = {'m': 2, 'M': 2, 'l': 2, 'L': 2, 'c': 6, 'C': 6}[cmd]
        while len(nums) < need:
            nums.append(float(toks[i])); i += 1
        if cmd in 'mM':
            cur = (nums[0], nums[1]) if cmd == 'M' else (cur[0] + nums[0], cur[1] + nums[1])
            if sub: out.append(sub)
            sub = [cur]; start = cur
            cmd = 'l' if cmd == 'm' else 'L'      # subsequent pairs are implicit linetos
        elif cmd in 'lL':
            cur = (nums[0], nums[1]) if cmd == 'L' else (cur[0] + nums[0], cur[1] + nums[1])
            sub.append(cur)
        else:  # c / C
            if cmd == 'c':
                c1 = (cur[0] + nums[0], cur[1] + nums[1])
                c2 = (cur[0] + nums[2], cur[1] + nums[3])
                p1 = (cur[0] + nums[4], cur[1] + nums[5])
            else:
                c1, c2, p1 = (nums[0], nums[1]), (nums[2], nums[3]), (nums[4], nums[5])
            SEG = 16
            for s in range(1, SEG + 1):
                tt = s / float(SEG); u = 1 - tt
                x = u*u*u*cur[0] + 3*u*u*tt*c1[0] + 3*u*tt*tt*c2[0] + tt*tt*tt*p1[0]
                y = u*u*u*cur[1] + 3*u*u*tt*c1[1] + 3*u*tt*tt*c2[1] + tt*tt*tt*p1[1]
                sub.append((x, y))
            cur = p1
    if sub: out.append(sub)
    return out

def paths_of(svg_text):
    """-> [(id, d)] in document order."""
    return [(m.group(2), m.group(1)) for m in
            re.finditer(r'<path\b[^>]*?\bd="([^"]+)"[^>]*?\bid="([^"]+)"', svg_text, re.S)]

def convert(path, mirror_x, name, hull_id):
    svg = io.open(path, encoding='utf-8').read()
    raw = paths_of(svg)
    shapes = [(pid, parse_path(d)) for pid, d in raw]

    hull = [s for pid, s in shapes if pid == hull_id][0]
    hx = [p[0] for sub in hull for p in sub]
    hy = [p[1] for sub in hull for p in sub]
    cx = (min(hx) + max(hx)) / 2.0
    cy = (min(hy) + max(hy)) / 2.0
    scale = 2.0 / (max(hx) - min(hx))          # hull spans -1..1 in x

    def xf(p):
        x = (p[0] - cx) * scale
        y = (p[1] - cy) * scale
        return (-x if mirror_x else x, y)

    print('static void %s(TArray<TArray<FVector2f>>& OutStrokes)' % name)
    print('{')
    allpts = []
    for pid, subs in shapes:
        for si, sub in enumerate(subs):
            pts = [xf(p) for p in sub]
            allpts += pts
            print('\t\t{ // %s%s  (%d pts)' % (pid, '' if len(subs) == 1 else '/%d' % si, len(pts)))
            print('\t\t\tstatic const FVector2f P[] = {')
            for k in range(0, len(pts), 4):
                row = ', '.join('{%.4ff,%.4ff}' % q for q in pts[k:k+4])
                print('\t\t\t\t' + row + ',')
            print('\t\t\t};')
            print('\t\t\tOutStrokes.Add(TArray<FVector2f>(P, UE_ARRAY_COUNT(P)));')
            print('\t\t}')
    print('}')
    print('')
    xs = [p[0] for p in allpts]; ys = [p[1] for p in allpts]
    sys.stderr.write('%s: x %.3f..%.3f  y %.3f..%.3f  (%d pts)\n'
                     % (name, min(xs), max(xs), min(ys), max(ys), len(allpts)))

base = r'E:\windowsgrejor\git\GoneSurfingUE5\GoneSurfing\Content\Images'
print('// GENERATED by Tools/svg2glyph.py from Content/Images/surfboard_*.svg. Do not hand-edit:')
print('// redraw the SVG and re-run the script. Points are normalised so the HULL spans x -1..1,')
print('// y by the same factor (aspect preserved), centred on the hull. The profile is mirrored so')
print('// the nose points +x, which is the direction the glyph travels on the pump card.')
print('')
convert(base + r'\surfboard_rear_view.svg', False, 'BuildTailOnShape', 'path1')
convert(base + r'\surfboard_profile.svg',   True,  'BuildSideOnShape', 'path1')
